namespace Notes.Api.Database;

using System;
using System.Linq;
using Notes.Api.Models;

public static class GenerateRandom
{
    public static string Content =>
        new string("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore."
            .Take(Random.Next(5, 100))
            .ToArray());

    public static User User => new User
    {
        Username = Username,
        Password = Password,
    };

    public static string Password => Guid.NewGuid().ToString();

    public static string Username => $"{GivenName} {Surname}";

    public static string GivenName => GivenNames[Random.Next(GivenNames.Length)];

    public static string Surname => Surnames[Random.Next(Surnames.Length)];

    private static readonly Random Random = new Random();

    private static readonly string[] Surnames = new string[]
    {
        "Smith",
        "Jones",
        "Taylor",
        "Brown",
        "Williams",
        "Wilson",
        "Johnson",
        "Davies",
        "Robinson",
        "Wright",
        "Thompson",
        "Evans",
        "Walker",
        "White",
        "Roberts",
        "Green",
        "Hall",
        "Wood",
        "Jackson",
        "Clarke",
    };

    private static readonly string[] GivenNames = new string[]
    {
        "Adie",
        "Angie",
        "Ashton",
        "Aubrey",
        "Barnes",
        "Barry",
        "Basil",
        "Bernadine",
        "Bethany",
        "Bette",
        "Betty",
        "Blanche",
        "Braden",
        "Bradley",
        "Brent",
        "Bret",
        "Brett",
        "Burdine",
        "Caden",
        "Cadence",
        "Carrington",
        "Charlene",
        "Charles",
        "Charlton",
        "Chay",
        "Chet",
        "Christopher",
        "Clinton",
        "Corina",
        "Corinna",
        "Cowden",
        "Daris",
        "Darleen",
        "Darlene",
        "Darnell",
        "Deb",
        "Demi",
        "Dennis",
        "Diamond",
        "Doreen",
        "Dorian",
        "Dorothy",
        "Dustin",
        "Earlene",
        "Elaine",
        "Elfriede",
        "Eli",
        "Emery",
        "Emory",
        "Evan",
        "Gabriel",
        "Georgiana",
        "Gladys",
        "Greenbury",
        "Gregory",
        "Greig",
        "Gwen",
        "Harley",
        "Hastings",
        "Hazel",
        "Heather",
        "Helton",
        "Henrietta",
        "Heston",
        "Holly",
        "Hulda",
        "India",
        "Irene",
        "Jackie",
        "Jade",
        "January",
        "Jean",
        "Jemma",
        "Jenny",
        "Jerald",
        "Jerrold",
        "Jerry",
        "Jessie",
        "Jethro",
        "Jigar",
        "Jill",
        "Jocelyn",
        "Jodie",
        "Joey",
        "Justine",
        "Kate",
        "Kathryn",
        "Keaton",
        "Kendra",
        "Kerr",
        "Kimball",
        "Kitty",
        "Kristy",
        "Kylie",
        "Laren",
        "Lawrence",
        "Lawson",
        "Leanne",
        "Lianne",
        "Louise",
        "Luci",
        "Lucius",
        "Lucretia",
        "Maddox",
        "Madeleine",
        "Malford",
        "Marlene",
        "Maud",
        "Melinda",
        "Melville",
        "Miley",
        "Millicent",
        "Mindi",
        "Mindy",
        "Moira",
        "Molly",
        "Mort",
        "Nancy",
        "Naomi",
        "Nelson",
        "Nevaeh",
        "Nigel",
        "Noel",
        "Osbert",
        "Ottilie",
        "Pamela",
        "Pascoe",
        "Patricia",
        "Percy",
        "Philip",
        "Philippa",
        "Pippa",
        "Poppy",
        "Quintus",
        "Rebecca",
        "Reynold",
        "Rhoda",
        "Riley",
        "Roland",
        "Rosaleen",
        "Rosalie",
        "Rosie",
        "Ruby",
        "Rupert",
        "Ruth",
        "Savannah",
        "Scarlett",
        "Schuyler",
        "Scott",
        "Sharon",
        "Sheridan",
        "Shiloh",
        "Sidney",
        "Stacy",
        "Sydney",
        "Tabitha",
        "Tammy",
        "Theodore",
        "Timothy",
        "Tracy",
        "Travis",
        "Trent",
        "Trudie",
        "Velma",
        "Vicary",
        "Violet",
        "Virgil",
        "Virginia",
        "Warren",
        "Whitney",
        "Whittaker",
        "Wilfried",
        "Woodrow",
    };
}